# Shows how the r-build-check.yml can be called from another repository.
name: call
on:
    push:
        branches: ['main']

jobs:
    build-check:
        uses: FertigLab/actions/.github/workflows/r-build-check.yml@main
