# Based on Github basic workflow and r-lib actions
name: r-build-check

on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - name: Check
        uses: r-lib/actions/check-r-package@v2
