# Based on Github basic workflow and r-lib actions
name: r-build-check
on:
  workflow_call:
    inputs:
      chargs:
        type: string
        description: 'check args to pass on'
        default: 'c("--no-manual")'
      r_devel:
        type: string
        default: 'false'

  workflow_dispatch:
    inputs:
      chargs:
        type: string
        description: 'check args to pass on'
        default: 'c("--no-manual")'
      r_devel:
        type: string
        default: 'false'

jobs:  
  define_matrix:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - name: R release and devel
        run: |
          echo 'r=["release", "devel"]' >> "$GITHUB_OUTPUT"
        if: ${{inputs.r_devel == 'true'}}

      - name: R release
        run: |
          echo 'r=["release"]' >> "$GITHUB_OUTPUT"
        if: ${{inputs.r_devel == 'false'}}

  r-build-check:
    needs: define_matrix
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r }})
    strategy:
      fail-fast: false
      matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]
          r: ${{ fromJSON(needs.define_matrix.outputs.r) }}
              
    steps:      
      - name: Configure git
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true
      - name: Install deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: ${{ inputs.chargs }}
